### ISSUE TITLE
Use database

### ISSUE THREAD

**Issue by Alexamakans** [Pluppen/HealtyBoiChallenge#6]
how about some [leveldb](https://github.com/google/leveldb)?
any plans?

**Comment by Pluppen** [comment]
LevelDB looks nice! My initial though was a simple sqlite db but that is maybe to hardcore

**Comment by donran** [comment]
This is high priority ticket, please implement this ASAP, preferably this week.

**Comment by Alexamakans** [comment]
will have this done tomorrow (monday)
